### ISSUE TITLE
Yeoman Generators problem on Node 8.1.0

### ISSUE THREAD

**Issue by NicholasSaayman** [Azure/generator-azuresfguest#3]
This is more informational as I would like to save others the time if they attempt to use this locally.

If you are using Node 8.1.0 the yeoman generators freeze. The behaviour is that the prompt stops accepting input.

Yeoman generators freeze with Node 8.1.0 #1026

I updated to Node 8.11.2 and all worked thereafter.

**Comment by suhuruli** [comment]
Sorry for the late response and thanks for the information!

**Comment by suhuruli** [comment]
Will put this into the README.md and close this issue.
